{{ $conf := .Values.ymreleasebot }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $conf.logging.configmap_name }}
data:
  logging_informer_new.conf: |
    [loggers]
    keys=root, informer

    [handlers]
    keys=consoleHandler

    [formatters]
    keys=myFormatter

    [logger_root]
    level=CRITICAL
    handlers=consoleHandler

    [logger_informer]
    level=INFO
    handlers=consoleHandler
    qualname=informer

    [handler_consoleHandler]
    class=StreamHandler
    formatter=myFormatter
    args=(sys.stdout,)

    [formatter_myFormatter]
    format={"message": "%(message)s", "level": "%(levelname)s", "app_name": "xerxes_informer", "app_type": "python", "log_type":"code", "es_index_name": "python-xerxes-main", "timestamp": "%(asctime)s"}
    datefmt=%Y-%m-%dT%H:%M:%S+0300
