---
## releaseot configuration

releasebot:
  name: 'releasebot-informer'
  app_type: 'python'
  app_name: 'releasebot'
  kafka_log_topic: 'yamoney_python_ymreleasebot'
  count_replicas: 1
  service_port: 80
  target_port: 8080
  image: 'docker-ym.nexus.yamoney.ru/yamoney/releasebot-informer'
  tag: 'latest'
  ingress:
    host: releasebot-informer
    path: /
    pathType: ImplementationSpecific
  logging:
    configmap_name: 'log-config-releasebot-informer'
  resources:
    requests:
      memory: 128Mi
      cpu: '100m'
    limits:
      memory: 512Mi
      cpu: '200m'
