## YMreleaseBot configuration

ymreleasebot:
  name: 'xerxes-informer'
  app_type: 'python'
  app_name: 'ymreleasebot'
  kafka_log_topic: 'yamoney_python_ymreleasebot'
  service_port: 8080
  count_replicas: 1
  image: 'docker-ym.nexus.yamoney.ru/yamoney/xerxes-informer'
  tag: <value>
  mysql:
    name: mysql
    port:
      name: mysql-client
      value: 3306
    ip: 10.200.51.2
  logging:
    configmap_name: 'log-config-ymreleasebot-informer'
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 512m
  secrets:
    mysql:
      name: 'mysql'
      pass: <value>
      user: <value>
    jira:
      name: 'jira'
      pass: <value>
      user: <value>
    telegram:
      name: 'telegram'
      value: <value>