{{ $conf := .Values.ymreleasebot }}
apiVersion: v1
data:
  pass: {{ $conf.secrets.mysql.pass }}
  user:  {{ $conf.secrets.mysql.user }}
kind: Secret
metadata:
  name: {{ $conf.secrets.mysql.name }}
type: Opaque
